# 🚗 Used Car Dataset – Data Cleaning & Exploration

**Dataset:** `car.csv` (used cars data)

**What this notebook covers:**
1. Importing libraries and loading the data
2. Taking a first look at the data (head / tail)
3. Checking for missing values
4. Understanding data types and basic statistics
5. Checking for and removing duplicates
6. Saving and downloading the cleaned file

**Columns:** `brand`, `model`, `transmission`, `age`, `fuel`, `engine`, `km`, `owner`, `price`, `location`, `mileage`, `power`, `seats`, `type`

## 1. Import Library
First, we import `pandas`, which we use to load and clean the data.

In [ ]:
import pandas as pd

## 2. Load the Data
Read the `car.csv` file into a DataFrame called `df` using `pd.read_csv()`.

In [ ]:
df=pd.read_csv("car.csv")

## 3. Preview the End of the Data – `tail()`
Displays the **last 5 rows** of the dataset to get an idea of its structure and values.

In [ ]:
df.tail()

,brand,model,transmission,age,fuel,engine,km,owner,price,location,mileage,power,seats,type
32195,datsun,redi go,manual,6.0,petrol,NaN,11500.0,1.0,292000.0,maharashtra,NaN,NaN,5.0,hatchback
32196,toyota,yaris,manual,6.0,petrol,NaN,73393.0,2.0,534000.0,karnataka,NaN,NaN,5.0,sedan
32197,volkswagen,ameo,manual,8.0,petrol,NaN,83810.0,2.0,424000.0,uttar pradesh,NaN,NaN,5.0,sedan
32198,hyundai,grand i10 nios,automatic,5.0,petrol,NaN,39162.0,1.0,685000.0,chandigarh,NaN,NaN,5.0,hatchback
32199,tata,tigor,manual,2.0,petrol,NaN,82009.0,2.0,392000.0,maharashtra,NaN,NaN,5.0,sedan

## 4. Missing Values (Boolean View)
`df.isnull()` returns `True` for missing cells and `False` for present ones.
This is the raw view of where data is missing across the whole dataset.

In [ ]:
df.isnull()

,brand,model,transmission,age,fuel,engine,km,owner,price,location,mileage,power,seats,type
0,False,False,False,False,False,False,False,False,False,True,True,True,True,True
1,False,False,False,False,False,False,False,False,False,True,True,True,True,True
2,False,False,False,False,False,False,False,False,False,True,True,True,True,True
3,False,False,False,False,False,False,False,False,False,True,True,True,True,True
4,False,False,False,False,False,False,False,False,False,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32195,False,False,False,False,False,True,False,False,False,False,True,True,False,False
32196,False,False,False,False,False,True,False,False,False,False,True,True,False,False
32197,False,False,False,False,False,True,False,False,False,False,True,True,False,False
32198,False,False,False,False,False,True,False,False,False,False,True,True,False,False
32199,False,False,False,False,False,True,False,False,False,False,True,True,False,False

## 5. Dataset Information
`df.info()` shows:
- Total rows and columns (32,200 rows × 14 columns)
- The **data type** of each column
- The **non-null count** per column, which hints at missing values

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32200 entries, 0 to 32199
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   brand         32199 non-null  object
 1   model         32199 non-null  object
 2   transmission  32200 non-null  object
 3   age           32199 non-null  float64
 4   fuel          32200 non-null  object
 5   engine        24068 non-null  float64
 6   km            32200 non-null  float64
 7   owner         16819 non-null  float64
 8   price         32200 non-null  float64
 9   location      13801 non-null  object
 10  mileage       21380 non-null  float64
 11  power         21273 non-null  float64
 12  seats         29353 non-null  float64
 13  type          8015 non-null   object
dtypes: float64(8), object(6)
memory usage: 3.4+ MB

## 6. Statistical Summary
`df.describe()` summarizes the numeric columns (`age`, `engine`, `km`, `owner`, `price`):
count, mean, standard deviation, min, quartiles (25% / 50% / 75%) and max.

This helps in spotting outliers and understanding the range of values.

In [ ]:
df.describe()

,age,engine,km,owner,price,mileage,power,seats
count,32199.000000,24068.000000,3.220000e+04,16819.000000,3.220000e+04,21380.000000,21273.000000,29353.000000
mean,7.120625,1489.872569,5.495269e+04,1.263452,7.347001e+05,19.305532,103.497647,5.233537
std,3.485577,520.916872,5.577145e+04,0.490463,7.037702e+05,4.418605,45.002260,0.707639
min,0.000000,72.000000,0.000000e+00,1.000000,4.000000e+04,0.000000,34.200000,0.000000
25%,4.000000,1197.000000,3.020825e+04,1.000000,3.850000e+05,16.500000,74.000000,5.000000
50%,7.000000,1248.000000,5.000000e+04,1.000000,5.510000e+05,19.010000,88.500000,5.000000
75%,9.000000,1591.000000,7.102075e+04,1.000000,7.920000e+05,22.320000,120.000000,5.000000
max,29.000000,5998.000000,6.500000e+06,4.000000,7.066000e+06,46.620600,600.000000,10.000000

## 7. Missing Values Count per Column
`df.isnull().sum()` gives the number of missing values in each column.

**Observation:** `type`, `location`, `owner`, `power`, `mileage` and `engine` have a large number of missing values, while `brand`, `model` and `age` have only 1 each.

In [ ]:
df.isnull().sum()

brand               1
model               1
transmission        0
age                 1
fuel                0
engine           8132
km                  0
owner           15381
price               0
location        18399
mileage         10820
power           10927
seats            2847
type            24185
dtype: int64

## 8. Shape of the Dataset
`df.shape` returns `(rows, columns)`. The dataset currently has **32,200 rows and 14 columns**.

In [ ]:
df.shape

(32200, 14)

## 9. Check for Duplicate Rows
`df.duplicated().sum()` counts the duplicate rows.

**Result:** `0`, so no duplicate rows were found.

In [ ]:
df.duplicated().sum()

np.int64(0)

## 10. Remove Duplicates
`drop_duplicates()` removes duplicate rows if there are any. This dataset had none, so the data remains unchanged.

In [ ]:
df = df.drop_duplicates()

## 11. Save the Cleaned Data
Save the cleaned DataFrame back to `car.csv`.
`index=False` ensures the index is not written as an extra column in the file.

In [ ]:
df.to_csv("car.csv", index=False)

## 12. Final Check – `head()`
Displays the **first 5 rows** of the cleaned data to confirm everything looks correct.

In [ ]:
df.head()

,brand,model,transmission,age,fuel,engine,km,owner,price,location,mileage,power,seats,type
0,mahindra,thar,manual,4.0,diesel,2184.0,11003.0,1.0,1231000.0,NaN,NaN,NaN,NaN,NaN
1,hyundai,verna,manual,6.0,petrol,1591.0,66936.0,1.0,786000.0,NaN,NaN,NaN,NaN,NaN
2,tata,harrier,manual,2.0,diesel,1956.0,27990.0,1.0,1489000.0,NaN,NaN,NaN,NaN,NaN
3,honda,city,automatic,1.0,petrol,1498.0,5061.0,1.0,1227000.0,NaN,NaN,NaN,NaN,NaN
4,ford,ecosport,manual,3.0,diesel,1498.0,23480.0,1.0,887000.0,NaN,NaN,NaN,NaN,NaN

## 13. Final Check – `tail()`
Displays the **last 5 rows** of the cleaned data as a final confirmation.

In [ ]:
df.tail()

,brand,model,transmission,age,fuel,engine,km,owner,price,location,mileage,power,seats,type
32195,datsun,redi go,manual,6.0,petrol,NaN,11500.0,1.0,292000.0,maharashtra,NaN,NaN,5.0,hatchback
32196,toyota,yaris,manual,6.0,petrol,NaN,73393.0,2.0,534000.0,karnataka,NaN,NaN,5.0,sedan
32197,volkswagen,ameo,manual,8.0,petrol,NaN,83810.0,2.0,424000.0,uttar pradesh,NaN,NaN,5.0,sedan
32198,hyundai,grand i10 nios,automatic,5.0,petrol,NaN,39162.0,1.0,685000.0,chandigarh,NaN,NaN,5.0,hatchback
32199,tata,tigor,manual,2.0,petrol,NaN,82009.0,2.0,392000.0,maharashtra,NaN,NaN,5.0,sedan

## 14. Download the File
Download the cleaned `car.csv` from Google Colab to your computer.

> ⚠️ `google.colab` works only in Colab, not in a local Jupyter environment.

In [ ]:
from google.colab import files
files.download("car.csv")

## ✅ Summary
- Dataset size: **32,200 rows × 14 columns**
- **Duplicates:** 0 (none found)
- **Missing values:** `type` (24,185), `location` (18,399), `owner` (15,381), `power` (10,927), `mileage` (10,820), `engine` (8,132), `seats` (2,847); `brand`, `model` and `age` have 1 each
- The data was saved to `car.csv` and downloaded